/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.util.*;
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        int rolls = 3;

        //roll(rolls);
        //duplicates(roll(rolls));
        averages(roll(rolls));




    }
    //rolls a dice n amount of times and returns an array of each roll
    public static int[] roll(int n) {
        int[] rollArray = new int [n];
        for (int i = 0; i<n; i++){

            rollArray[i] = rand();
            System.out.println("rollArray[i]" + rollArray[i]);
        }
        return(rollArray);

    }
    //returns a random int 1-6
    public static int rand() {
        while (true) {
            int dice = new Random().nextInt(6);

            if (dice != 0) {
                System.out.println("dice" + dice);
                return(dice);


            }

        }

    }
//   two for loops check eachother for duplicates returning boolean
    public static boolean duplicates(int[] array) {
        for (int i = 0; i<array.length; i++){
            for (int j = 0; i<array.length; j++){
                if (array[i] == array[j]) {
                    System.out.println("duplicates yay");
                    return (true);
                }
            }
        }
        System.out.println("no dup");
        return(false);
    }
    public static double averages(int[] array){
        int total = 0;
        double average = 0;
        for (int i = 0; i<array.length; i++){

            total += array[i];
        }
        average = total/array.length;
        System.out.println("average is " + average);
        return(average);
    }

}
