/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.util.ArrayList;
import java.util.LinkedList;

public class Restaurant implements HasReviews {
//Global variable
    public String name;
    public double stars;
    public String price;
    public ArrayList<Review> reviewList;
//Restaraunt constructor takes a name and price "$"
    public Restaurant(String name, String price) {
        this.name = name;
        this.stars = 0;
        this.price = price;
        this.reviewList = new ArrayList<Review>();
    }
//addReview method takes in a review and adds it to the restaurant and then replaces stars of the restaurant with avgStars()
    public void addReview(Review review) {

        this.reviewList.add(review);
        review.reviewedName = this;
        stars = avgStars();
    }
    //avgStars adds up all the review star votes and returns average
    public Double avgStars(){

        int size = reviewList.size();
        int total = 0;
        for (Review s : reviewList) {
           total +=  s.stars;
        }

        return (double)total/(double)size;
    }
//toString stringify my restaurant objects
    public String toString(){
        return "Restaurant name: " + this.name + " Rating: " + this.stars + " Cost: " +this.price;
    }

}



