import java.util.ArrayList;


/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.util.ArrayList;
import java.util.LinkedList;

public class Theater {


    //Global variable
    public String name;
    public double stars;
    public String price;
    public ArrayList<String> movieList;
    public ArrayList<Review> reviewList;

    //Theater constructor takes a name and price "$"
    public Theater(String name, String price) {
        this.name = name;
        this.stars = 0;
        this.price = price;
        this.movieList = new ArrayList<String>();
        this.reviewList = new ArrayList<Review>();
    }

    //addReview method takes in a review and adds it to the restaurant and then replaces stars of the restaurant with avgStars()
    public void addMovieReview(MovieReview review) {

        this.reviewList.add(review);
        review.reviewedName = this;
        stars = avgStars();
    }

    public void addMovie(String movie) {

        this.movieList.add(movie);

    }

    public void removeMovie(String movie) {
        this.movieList.remove(movie);

    }


    //avgStars adds up all the review star votes and returns average
    public Double avgStars() {

        int size = reviewList.size();
        int total = 0;
        for (Review s : reviewList) {
            total += s.stars;
        }

        return (double) total / (double) size;
    }

    //toString stringify my restaurant objects
    public String toString() {
        return "Theater name: " + this.name + " Rating: " + this.stars + " Cost: " + this.price + "Playing: " + movieList;
    }

}





