import java.io.BufferedReader;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
//run
public class App {


    public static void main(String[] args) {
        Path imagePath = FileSystems.getDefault().getPath("resources", "crest.bmp");

        Bitmap bmp = new Bitmap(imagePath);

        bmp.flipHorizontally();

        bmp.save(FileSystems.getDefault().getPath("resources", "crest.bmp"));

        }
}
