/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.*;
import java.lang.Iterable;

public class RestaurantTest {



    @Test
    public void testToString() {
        Restaurant testRestaurant = new Restaurant ("Mcdonalds", "$");
        String stringifiedRestaurant = "Restaurant name: Mcdonalds Rating: 0.0 Cost: $";


        assertEquals("Mcdonalds", testRestaurant.name);
        assertEquals(stringifiedRestaurant, testRestaurant.toString());
    }

    @Test
    public void addReview() {
        Restaurant Mcdonalds = new Restaurant ("Mcdonalds", "$");
        Review mcReview1 = new Review ("Mason Bassett", 5, "I'm loving it");
        Review mcReview2 = new Review ("Mason Bassett", 4, "I'm loving it");
        Review mcReview3 = new Review ("Mason Bassett", 3, "I'm loving it");

        Mcdonalds.addReview(mcReview1);
        Mcdonalds.addReview(mcReview2);
        Mcdonalds.addReview(mcReview3);
        double expected = 4.0;
        assertTrue(Mcdonalds.stars == expected);
    }

    @Test
    public void avgStars() {
        Restaurant Mcdonalds = new Restaurant ("Mcdonalds", "$");
        Review mcReview1 = new Review ("Mason Bassett", 5, "I'm loving it");
        Review mcReview2 = new Review ("Mason Bassett", 4, "I'm loving it");
        Review mcReview3 = new Review ("Mason Bassett", 3, "I'm loving it");

        Mcdonalds.addReview(mcReview1);
        Mcdonalds.addReview(mcReview2);
        Mcdonalds.addReview(mcReview3);
        double expected = 4.0;
        assertTrue(Mcdonalds.stars == expected);
    }


}
