/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;

public class App {



    public static String checkFile (String fileName) {

        Charset charset = Charset.forName("US-ASCII");
        StringBuffer resultStringBuffer = new StringBuffer();

        try(BufferedReader reader = Files.newBufferedReader(FileSystems.getDefault().getPath("resources", fileName),charset)) {
            String currentLine = "";
            int lineNumber = 1;
            while(currentLine != null) {



                if (!currentLine.endsWith(";") || !currentLine.endsWith("}") || !currentLine.endsWith("{") || !currentLine.contains("if") || !currentLine.contains("else")) {

                    resultStringBuffer.append("Line " + lineNumber + ": Missing semicolon" + "\n");
                }




                currentLine = reader.readLine();
                lineNumber ++;

            }
            return resultStringBuffer.toString();
        } catch (IOException e) {
            System.out.println(e);
            return null;
        }

    }



}


